---
- hosts: all

  roles:
    - chruby
    - ruby-install
    - { role: atom, atom_tmp_deb: /home/vagrant/atom.deb }
    - { role: rubies, ruby_version: 2.1.3 }

  tasks:

    - name: install required packages
      apt: name={{ item }} state=present
      with_items:
        - git
        - tree
        - vim
        - terminator
        - nodejs
      sudo: true

    # VIM
    - name: create .vim contents
      file: path={{ item }} group=vagrant owner=vagrant state=directory
      with_items:
      - /home/vagrant/.vim/autoload
      - /home/vagrant/.vim/bundle

    - name: download pathogen
      command: curl -Sso /home/vagrant/.vim/autoload/pathogen.vim https://raw.githubusercontent.com/tpope/vim-pathogen/master/autoload/pathogen.vim creates=/home/vagrant/.vim/autoload/pathogen.vim

    - name: clone NERDTree
      git: repo=https://github.com/scrooloose/nerdtree.git dest=/home/vagrant/.vim/bundle/nerdtree update=yes

    # Dot files
    - file: path=/home/vagrant/{{ item }} src=/home/vagrant/dotfiles/{{ item }} state=link force=yes
      with_items:
      - .gitconfig
      - .vimrc
      - .bashrc
